server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springcloud-config.git
          # 忽略本地配置使用配置文件属性
          ignoreLocalSshSettings: true
          # 本地密钥对密码
          passphrase: 12345
          # hostKey:
          # hostKeyAlgorithm: ssh-rsa
          private-key: |
                        -----BEGIN RSA PRIVATE KEY-----
                        Proc-Type: 4,ENCRYPTED
                        DEK-Info: AES-128-CBC,02C276AC96ED7AF6F393F696434F25F2

                        lXyvmvnO6ZWpS9udTzIQYJ91YL+snVL/mU26mHdjyBTSU9sXyvNgxVYseF+ynS4D
                        KeVxKOFvj1a31NgjnzetlHm87AE+jNQkQ5PmpERwet0kDV3Rfa5M7g61M9kufA0S
                        U4FAWMf+ENJgERI5nu19wZhZFbmOVEigXI5pM3pMluoOv/5Kfi32Cl1AxrLtZk/A
                        el0DLVqeEkwwxQczdXscxdtD/Gz3H/8SvZpGOkskGZ2VJpJE0TWAref4mrT6u8YL
                        YK6l2OUI33Rpwfx2F+IScxko5TQXsIgAiqsj24rgOJocM3DPoaGHY54IE+hNvSZB
                        aBh1XPDZ5h6NRa0Mj3uS64/NQWWPwoCgj/YsbotGitwuIsFsA4UexeFyT99iCUMi
                        350XX2qxuaXPwJZQ+sBQdXi+slgfDRdeSjy5PfIXekseF0z3tvV0aYTY3Dm1PxXn
                        X2nwQDH8iX2f3gUb82qFnCsyLt2oFM0Qi9cDxZ7rDW6FlOdzAks+9i9sr09qat0i
                        DWoaqQX6gAHiUyy5zxNDZRZBfQpjgCcAfDLy9xKFy5VqEYjb8AGkyeXfGi8Sq8b9
                        KDUdnQ2VUuQnNi1En8jKzyAOOwX4sI2cV9PPQWv5qaf4D+nSn0E0civ48BP0bSMe
                        ZwfKPxt5+0mWFozyb2E8BAYxAigIt6k4jN2CFlGSh9IG+yfyBhw2Ou2V4GfY3oFq
                        qx4cBNsxieGfJuX/n5i4ladK5Q9evPj1sOEU2Rg222OZN96QZ+wVn77ll3KqtXKF
                        dv2wMOLWgjHevU+LJNF01x8LW5JwLIZFEQ6OlCNMYzpXjlE8hGUL9RLgwohEvnvt
                        1ZAnEcee0yLKLfdhnE452AsWitNeYg3s7RLVgVOiIzpVtE9GUMc3LttrBIyQI+zm
                        bhlFWhVQeZKXtL8KyovOEMDmeZXAb1lmSlf/4vYTKAqbSKiLiRY3S2CJROTnFhFL
                        aS7r4JOmy8qdWB4O6kuYoAbVuMba6ijWi03TH+dyz0wDWS6+5eVW4DVaDO++y0Fb
                        Z1gsYdy7I9edrisDNYSja106jsFudvS34wYDa/cup9FFjrBeFaNnO5PMGm3km2DF
                        Qj5x+XrxszalDX3pfbNJ6xRWPdZgoT08QVzEvzjSs1dswx9eGYACIHGecGIkiOfQ
                        GTi0BFiZp/Mza0a/L0fAIsvTdvu+9GSYjHQYGSanQ4UhwCl22DA5uZ2W2bdJrOsL
                        4LDNqSIAnyLO7XWt1tF+Ul7rFtnCOekpVa/q3VPtHp+ZxvN38LbntON/wYWxOLjF
                        britJyqjnCVEpamXTCu6vzQgYk4PyEGNGtz97J5klUqMbC/d3AaMBHVp6XbDcAoV
                        z/7TGSw+y5koUb1qX5qSFeHWuR11qv4xXnAZuAFxEgOOtmCoT9hvZWGvLOIwORgk
                        awejbaVeHH4FJSSzrNYJs1VtQOw5DKbkXhPhz4gHeReAlvdoxqzzY1rlUW0npFNo
                        Q5doYv1pqJVAMoJ8PutwO97ug0e1DdcJUYglYEOeAnE9wzWcoL0I1mNDNnXSEBKv
                        PHED+v3fUAiNbx6KJJp1wd9N2rCN1/zxvUmJF9CqWwNDmn0jr4wMDzHPfsHX3UHC
                        dh4wtpLUaGPm4KYyI3TFd0XPHPgCi1cN7gik+Y4bb3zbd2RcHOOA3tZUPEpRaE9R
                        DJBLRPXO8nfEK/z8YGNR7wxjOTsT2GQlXhuc3Xb8LhPxKJpxaU07SfN/hv3M8oU9
                        7wh0h1zISaTsHCBuFHgSCjAG8mv+5m6UZfFAYLGAMtUvdu0on5oNOXjM48ehiWwx
                        81gA1xr9rooUWG5nGzO7sdcGtm0hUvoovZEgBAhVI2ZnOMgDLXvh4TJmbgA1MK54
                        gvYBHQ9sf1V1KOpfpBE/kM0eYNoId/LZ9tiFCz4JLgKHpJ64lJAorJ4AkCXnKXzX
                        XqY7fs4zfBgntNXX4wfQ3q0TaJVPTdMBFBTLDOOwo109YuOhmqenBOYUvSJjksI8
                        X8jjNr8PVb756vGJIqdWo4lt00CIRhkgvVaTVhE7PW4yoGbcooCva986psyUBrg1
                        huqLjBIg5wi+UYi3g0FFTq+i+cMpUtZDUPgtpg+fBd2qGrPUGJpgIie9reUkWVfN
                        MFwglwkaTf6JofjCvhjOLLRiaKNwzlBarIE5uM7FsbcO1UcPLsXdd3xF2Q11UkqI
                        9n9H8ahCRralzr36XT8RkEHRyvmuzcCJxHzTZngEQQ8rztgq9tI1CAOrfJqU97Q8
                        ldkPKBqa0gXxVxhJ0/rmwQuvEgCfZO/G25vKm9zbNzeVHrNIhlP+xZa9lTmefDIw
                        5+Icf3vaVln8bCdrVYuVID2v1vRgKqBgBrSj/TlCnM+X6wdB1uVOS84hclR2I8/q
                        wWwI52hdSxd2K/Q37gOdy0D0eS++5tvXVAlSkZvhr/0BgRS9Bd+Ou6k/0j2FTfpW
                        TW795wj2Jkp4QuDR1v5u6OABwzQ8IDv5Wa0mmzCADqMD1re2dr15cyf23sLsdW5v
                        qs6qtwCXEI1YMuCdLr4XyoHJKg3oLAWsnkG5dED2Vw6OOr0kx9/9HQD722i0Jeva
                        m3L06SUFNZkcZfwMXce8mYeHMiYh54x7Nk2dAZAteYTd2vwoZNA0e7krsByZ7b+0
                        +UuFn2xYGjN4ALZ1BBp/6I7xsKTjApttjZ3mhLCTAj2plKXFm4AyvyaQl7K0poiR
                        vz0Bz2NW14xxowOLGlPNNn4hjkKzx47tfR+5byf1HCcUbRuH7YKqNkAw77tRkJuC
                        VuayQnmXribtW8Jyipq6LJlczDVdQsg0E5KvayesUVSYuIhrgx1eBJwVOUq+9Rng
                        38B4nWbBM/8RVgmN6eNnlOHL9oQ9ZtKlRD/p8kFH++jkuqgskN6+jCIS+X3yRqjn
                        4HnC1sY0evGhxqcg+hHK1Z9X399pKEVC2zz1IUQXeUaNnQq6adfg/4jbA6hDgIXB
                        SthfTJ25P2Pu6Ydrz2kh2kNu4w5ycoIqEpJ+GiK54o8fdo2heL2f92ls3hFoR+x3
                        XuaOC7tWw1lCS4WKJmm2FByskmpY5wxGdkWHvZolwpDUnWH49vyHPs/5nABhHjbA
                        bpJsBGQy+XPXLukc3M5P7S4j1HyWAWNZVZnRzBH35cL7mvHrBnafWilbmo0Gs4S6
                        -----END RSA PRIVATE KEY-----
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master
  # rabbitmq 相关配置
  rabbitmq:
    host: 192.168.235.104
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

# rabbitmq 相关配置，暴露 bus 刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'