server:
  port: 8401

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp-tx-group
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.136:3306/seata_order?useSSL=false
    username: liyh1928
    password: 123456

feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml